import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SessionProvider from "next-auth"
import Sidebar from "@/components/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative lg:flex h-[100vh] base-text">
          <div className="absolute left-0 top-0 z-10 lg:relative  ">
            <Sidebar />
          </div>

          <main
            className={`transition-all duration-300 ease-in-out flex-1 ml-[80px] lg:ml-0 h-screen overflow-y-auto `}
          >
            <div className="flex-1 min-h-[88vh]">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
